#!/bin/bash -e

#TODO: port needs to actually do the port addition e.g. -p 1 => +1 to port numbers

existing="yes"
new_thing="pane"
port=0
extra_config=~/.lrd-dev-tmux.conf

if [ -z $TMUX ]; then
  existing="no"
fi

if tmux list-windows -F '#{window_name}' | egrep 'Dev Servers|Grunt Watch|Backend Server|Sidekiq'; then
  echo "It looks like there are already windows open for this tmux?"
  exit 2
fi

while getopts Pw option; do
  case $option in
    P) new_thing="pane";;
  w) new_thing="window";;

esac
done

rake preflight || exit 1

case $new_thing in
  pane)
    if [ $existing == "yes" ]; then
      tmux new-window -n "Dev Servers" -c frontend 'bundle exec node_modules/.bin/grunt watch:develop'
    else
      tmux new-session -d -n "Dev Servers" -c frontend 'bundle exec node_modules/.bin/grunt watch:develop'
    fi
    tmux set-window-option -t "Dev Servers" remain-on-exit on

    tmux split-window -c backend 'bundle exec sidekiq'
    tmux split-window -c backend 'bundle exec rails server'

    tmux select-layout -t "Dev Servers" tiled
    ;;
  window)
    if [ $existing == "yes" ]; then
      tmux new-window -c frontend -n "Grunt Watch" 'bundle exec node_modules/.bin/grunt watch:develop'
    else
      tmux new-session -d -c frontend -n "Grunt Watch" 'bundle exec node_modules/.bin/grunt watch:develop'
    fi
    tmux set-window-option -t "Grunt Watch" remain-on-exit on

    tmux new-window -c backend -n "Backend Server" 'bundle exec rails server'
    tmux set-window-option -t "Backend Server" remain-on-exit on

    tmux new-window -c backend -n "Sidekiq" 'bundle exec sidekiq'
    tmux set-window-option -t "Sidekiq" remain-on-exit on
esac

if [ -f $extra_config ]; then
  echo Loading $extra_config
  tmux source-file $extra_config
else
  echo No $extra_config to load
fi

if [ $existing != "yes" ]; then
  tmux attach-session -d
fi

rake develop:launch_browser
