source "https://rubygems.org"

gem 'rails', "~> 4.2.2"

# gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'xing_backend_token_auth', '~> 0.1.31'

gem 'xing-backend', '~> 0.0.18'
# until next blank line: should move to xing-backend
# but there are several instances where there are rake tasks to be extracted 
# first
gem 'active_model_serializers'
gem 'rails-rfc6570', '~> 0.1'
gem 'pg'
gem "sanitize"
gem 'rack-cors', :require => 'rack/cors'
gem 'sidekiq'
gem 'sinatra', '>= 1.3.0', :require => nil
gem 'hash_validator'

# These are related to authentication
# New gem?
gem 'devise'
gem 'cancancan'

# Is BT part of Xing?
gem 'bibliotech'

# For sitemap? Own gem?
gem "typhoeus"



#gem 'xing-cms-backend'
#gem 'awesome_nested_set'
#gem "babosa"

group :development, :test do
  gem "rspec", "~> 3.1.0"
  gem "rspec-rails"
  gem 'rspec-activemodel-mocks'
  gem 'waterpig'
  gem "factory_girl_rails"
  gem 'annotate'
  gem 'simplecov'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'capybara-email'
  gem 'database_cleaner'
  gem 'byebug'
  gem 'cadre'
end

group :test do
  gem 'json_spec'
end

group :development do
  gem "populator"
  gem "faker"
  gem "pivotal-github"
end
