source "https://rubygems.org"

gem 'rails', "~> 4.1.9"

# gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'pg'
gem 'devise'
gem 'awesome_nested_set'
gem 'carrierwave'
gem "rmagick", require: false
gem "sanitize"
gem "babosa"
gem 'active_model_serializers'
gem 'rails-observers'
gem 'cancancan'
gem 'devise_token_auth', :github => 'hannahhoward/devise_token_auth'
gem 'bibliotech'
gem 'rails-rfc6570', '~> 0.1'
gem 'rack-cors', :require => 'rack/cors'
gem 'sidekiq'
gem 'sinatra', '>= 1.3.0', :require => nil
gem "typhoeus"
gem 'hash_validator'

group :development, :test do
  gem "rspec", "~> 3.0.0"
  gem "rspec-rails"
  gem 'rspec-activemodel-mocks'
  gem 'rspec-steps'
  gem 'waterpig', ">= 0.6.1"
  gem "factory_girl_rails"
  gem 'annotate'
  gem 'simplecov'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'capybara-email'
  gem 'database_cleaner'
  gem 'byebug'
  gem 'cadre'
end

group :test do
  gem 'json_spec'
end

group :development do
  gem "populator"
  gem "faker"
  gem "pivotal-github"
end
