source "https://rubygems.org"

gem 'rails', "~> 4.1"

# gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'pg'
gem 'devise'
gem 'awesome_nested_set', :git => 'https://github.com/collectiveidea/awesome_nested_set'
gem 'jquery-rails'
gem 'carrierwave'
gem 'zeroclipboard-rails'
gem "rmagick", require: false

group :development, :test do
  gem "rspec", "< 3.0.0"
  gem "rspec-rails", "< 3.0.0"
  gem "factory_girl_rails"
  gem 'annotate'
  gem 'simplecov'
  gem 'capybara'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'byebug'
  gem 'cadre'
end

group :development do
  gem "populator"
  gem "faker"
  gem "pivotal-github"
  gem 'sass-rails-source-maps', :git => "git@github.com:LRDesign/sass-rails-source-maps.git"
end
