source "https://rubygems.org"

gem 'rails', "~> 4.1"

# gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'pg'
gem 'devise'
gem 'awesome_nested_set', :git => 'https://github.com/collectiveidea/awesome_nested_set'
gem 'carrierwave'
gem "rmagick", require: false
gem "sanitize"
gem "babosa"
gem 'active_model_serializers'
gem 'cancancan'

group :development, :test do
  gem "rspec", "< 3.0.0"
  gem "rspec-rails", "< 3.0.0"
  gem "factory_girl_rails"
  gem 'annotate'
  gem 'simplecov'
  gem 'capybara'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'byebug'
  gem 'cadre'
end

group :test do
  gem 'json_spec'
end

group :development do
  gem "populator"
  gem "faker"
  gem "pivotal-github"
end
