require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConsumerResearchersController do

  # This should return the minimal set of attributes required to create a valid
  # ConsumerResearcher. As you add validations to ConsumerResearcher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "consumer_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConsumerResearchersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all consumer_researchers as @consumer_researchers" do
      consumer_researcher = ConsumerResearcher.create! valid_attributes
      get :index, {}, valid_session
      assigns(:consumer_researchers).should eq([consumer_researcher])
    end
  end

  describe "GET show" do
    it "assigns the requested consumer_researcher as @consumer_researcher" do
      consumer_researcher = ConsumerResearcher.create! valid_attributes
      get :show, {:id => consumer_researcher.to_param}, valid_session
      assigns(:consumer_researcher).should eq(consumer_researcher)
    end
  end

  describe "GET new" do
    it "assigns a new consumer_researcher as @consumer_researcher" do
      get :new, {}, valid_session
      assigns(:consumer_researcher).should be_a_new(ConsumerResearcher)
    end
  end

  describe "GET edit" do
    it "assigns the requested consumer_researcher as @consumer_researcher" do
      consumer_researcher = ConsumerResearcher.create! valid_attributes
      get :edit, {:id => consumer_researcher.to_param}, valid_session
      assigns(:consumer_researcher).should eq(consumer_researcher)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConsumerResearcher" do
        expect {
          post :create, {:consumer_researcher => valid_attributes}, valid_session
        }.to change(ConsumerResearcher, :count).by(1)
      end

      it "assigns a newly created consumer_researcher as @consumer_researcher" do
        post :create, {:consumer_researcher => valid_attributes}, valid_session
        assigns(:consumer_researcher).should be_a(ConsumerResearcher)
        assigns(:consumer_researcher).should be_persisted
      end

      it "redirects to the created consumer_researcher" do
        post :create, {:consumer_researcher => valid_attributes}, valid_session
        response.should redirect_to(ConsumerResearcher.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved consumer_researcher as @consumer_researcher" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumerResearcher.any_instance.stub(:save).and_return(false)
        post :create, {:consumer_researcher => { "consumer_id" => "invalid value" }}, valid_session
        assigns(:consumer_researcher).should be_a_new(ConsumerResearcher)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumerResearcher.any_instance.stub(:save).and_return(false)
        post :create, {:consumer_researcher => { "consumer_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested consumer_researcher" do
        consumer_researcher = ConsumerResearcher.create! valid_attributes
        # Assuming there are no other consumer_researchers in the database, this
        # specifies that the ConsumerResearcher created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ConsumerResearcher.any_instance.should_receive(:update).with({ "consumer_id" => "1" })
        put :update, {:id => consumer_researcher.to_param, :consumer_researcher => { "consumer_id" => "1" }}, valid_session
      end

      it "assigns the requested consumer_researcher as @consumer_researcher" do
        consumer_researcher = ConsumerResearcher.create! valid_attributes
        put :update, {:id => consumer_researcher.to_param, :consumer_researcher => valid_attributes}, valid_session
        assigns(:consumer_researcher).should eq(consumer_researcher)
      end

      it "redirects to the consumer_researcher" do
        consumer_researcher = ConsumerResearcher.create! valid_attributes
        put :update, {:id => consumer_researcher.to_param, :consumer_researcher => valid_attributes}, valid_session
        response.should redirect_to(consumer_researcher)
      end
    end

    describe "with invalid params" do
      it "assigns the consumer_researcher as @consumer_researcher" do
        consumer_researcher = ConsumerResearcher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumerResearcher.any_instance.stub(:save).and_return(false)
        put :update, {:id => consumer_researcher.to_param, :consumer_researcher => { "consumer_id" => "invalid value" }}, valid_session
        assigns(:consumer_researcher).should eq(consumer_researcher)
      end

      it "re-renders the 'edit' template" do
        consumer_researcher = ConsumerResearcher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumerResearcher.any_instance.stub(:save).and_return(false)
        put :update, {:id => consumer_researcher.to_param, :consumer_researcher => { "consumer_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested consumer_researcher" do
      consumer_researcher = ConsumerResearcher.create! valid_attributes
      expect {
        delete :destroy, {:id => consumer_researcher.to_param}, valid_session
      }.to change(ConsumerResearcher, :count).by(-1)
    end

    it "redirects to the consumer_researchers list" do
      consumer_researcher = ConsumerResearcher.create! valid_attributes
      delete :destroy, {:id => consumer_researcher.to_param}, valid_session
      response.should redirect_to(consumer_researchers_url)
    end
  end

end
