require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DemoAnswersController do

  # This should return the minimal set of attributes required to create a valid
  # DemoAnswer. As you add validations to DemoAnswer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "text" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DemoAnswersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all demo_answers as @demo_answers" do
      demo_answer = DemoAnswer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:demo_answers).should eq([demo_answer])
    end
  end

  describe "GET show" do
    it "assigns the requested demo_answer as @demo_answer" do
      demo_answer = DemoAnswer.create! valid_attributes
      get :show, {:id => demo_answer.to_param}, valid_session
      assigns(:demo_answer).should eq(demo_answer)
    end
  end

  describe "GET new" do
    it "assigns a new demo_answer as @demo_answer" do
      get :new, {}, valid_session
      assigns(:demo_answer).should be_a_new(DemoAnswer)
    end
  end

  describe "GET edit" do
    it "assigns the requested demo_answer as @demo_answer" do
      demo_answer = DemoAnswer.create! valid_attributes
      get :edit, {:id => demo_answer.to_param}, valid_session
      assigns(:demo_answer).should eq(demo_answer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DemoAnswer" do
        expect {
          post :create, {:demo_answer => valid_attributes}, valid_session
        }.to change(DemoAnswer, :count).by(1)
      end

      it "assigns a newly created demo_answer as @demo_answer" do
        post :create, {:demo_answer => valid_attributes}, valid_session
        assigns(:demo_answer).should be_a(DemoAnswer)
        assigns(:demo_answer).should be_persisted
      end

      it "redirects to the created demo_answer" do
        post :create, {:demo_answer => valid_attributes}, valid_session
        response.should redirect_to(DemoAnswer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved demo_answer as @demo_answer" do
        # Trigger the behavior that occurs when invalid params are submitted
        DemoAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:demo_answer => { "text" => "invalid value" }}, valid_session
        assigns(:demo_answer).should be_a_new(DemoAnswer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DemoAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:demo_answer => { "text" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested demo_answer" do
        demo_answer = DemoAnswer.create! valid_attributes
        # Assuming there are no other demo_answers in the database, this
        # specifies that the DemoAnswer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DemoAnswer.any_instance.should_receive(:update).with({ "text" => "MyString" })
        put :update, {:id => demo_answer.to_param, :demo_answer => { "text" => "MyString" }}, valid_session
      end

      it "assigns the requested demo_answer as @demo_answer" do
        demo_answer = DemoAnswer.create! valid_attributes
        put :update, {:id => demo_answer.to_param, :demo_answer => valid_attributes}, valid_session
        assigns(:demo_answer).should eq(demo_answer)
      end

      it "redirects to the demo_answer" do
        demo_answer = DemoAnswer.create! valid_attributes
        put :update, {:id => demo_answer.to_param, :demo_answer => valid_attributes}, valid_session
        response.should redirect_to(demo_answer)
      end
    end

    describe "with invalid params" do
      it "assigns the demo_answer as @demo_answer" do
        demo_answer = DemoAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DemoAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => demo_answer.to_param, :demo_answer => { "text" => "invalid value" }}, valid_session
        assigns(:demo_answer).should eq(demo_answer)
      end

      it "re-renders the 'edit' template" do
        demo_answer = DemoAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DemoAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => demo_answer.to_param, :demo_answer => { "text" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested demo_answer" do
      demo_answer = DemoAnswer.create! valid_attributes
      expect {
        delete :destroy, {:id => demo_answer.to_param}, valid_session
      }.to change(DemoAnswer, :count).by(-1)
    end

    it "redirects to the demo_answers list" do
      demo_answer = DemoAnswer.create! valid_attributes
      delete :destroy, {:id => demo_answer.to_param}, valid_session
      response.should redirect_to(demo_answers_url)
    end
  end

end
