require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScreenerAnswersController do

  # This should return the minimal set of attributes required to create a valid
  # ScreenerAnswer. As you add validations to ScreenerAnswer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "text" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScreenerAnswersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all screener_answers as @screener_answers" do
      screener_answer = ScreenerAnswer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:screener_answers).should eq([screener_answer])
    end
  end

  describe "GET show" do
    it "assigns the requested screener_answer as @screener_answer" do
      screener_answer = ScreenerAnswer.create! valid_attributes
      get :show, {:id => screener_answer.to_param}, valid_session
      assigns(:screener_answer).should eq(screener_answer)
    end
  end

  describe "GET new" do
    it "assigns a new screener_answer as @screener_answer" do
      get :new, {}, valid_session
      assigns(:screener_answer).should be_a_new(ScreenerAnswer)
    end
  end

  describe "GET edit" do
    it "assigns the requested screener_answer as @screener_answer" do
      screener_answer = ScreenerAnswer.create! valid_attributes
      get :edit, {:id => screener_answer.to_param}, valid_session
      assigns(:screener_answer).should eq(screener_answer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScreenerAnswer" do
        expect {
          post :create, {:screener_answer => valid_attributes}, valid_session
        }.to change(ScreenerAnswer, :count).by(1)
      end

      it "assigns a newly created screener_answer as @screener_answer" do
        post :create, {:screener_answer => valid_attributes}, valid_session
        assigns(:screener_answer).should be_a(ScreenerAnswer)
        assigns(:screener_answer).should be_persisted
      end

      it "redirects to the created screener_answer" do
        post :create, {:screener_answer => valid_attributes}, valid_session
        response.should redirect_to(ScreenerAnswer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved screener_answer as @screener_answer" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenerAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:screener_answer => { "text" => "invalid value" }}, valid_session
        assigns(:screener_answer).should be_a_new(ScreenerAnswer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenerAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:screener_answer => { "text" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested screener_answer" do
        screener_answer = ScreenerAnswer.create! valid_attributes
        # Assuming there are no other screener_answers in the database, this
        # specifies that the ScreenerAnswer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScreenerAnswer.any_instance.should_receive(:update).with({ "text" => "MyText" })
        put :update, {:id => screener_answer.to_param, :screener_answer => { "text" => "MyText" }}, valid_session
      end

      it "assigns the requested screener_answer as @screener_answer" do
        screener_answer = ScreenerAnswer.create! valid_attributes
        put :update, {:id => screener_answer.to_param, :screener_answer => valid_attributes}, valid_session
        assigns(:screener_answer).should eq(screener_answer)
      end

      it "redirects to the screener_answer" do
        screener_answer = ScreenerAnswer.create! valid_attributes
        put :update, {:id => screener_answer.to_param, :screener_answer => valid_attributes}, valid_session
        response.should redirect_to(screener_answer)
      end
    end

    describe "with invalid params" do
      it "assigns the screener_answer as @screener_answer" do
        screener_answer = ScreenerAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenerAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => screener_answer.to_param, :screener_answer => { "text" => "invalid value" }}, valid_session
        assigns(:screener_answer).should eq(screener_answer)
      end

      it "re-renders the 'edit' template" do
        screener_answer = ScreenerAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenerAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => screener_answer.to_param, :screener_answer => { "text" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested screener_answer" do
      screener_answer = ScreenerAnswer.create! valid_attributes
      expect {
        delete :destroy, {:id => screener_answer.to_param}, valid_session
      }.to change(ScreenerAnswer, :count).by(-1)
    end

    it "redirects to the screener_answers list" do
      screener_answer = ScreenerAnswer.create! valid_attributes
      delete :destroy, {:id => screener_answer.to_param}, valid_session
      response.should redirect_to(screener_answers_url)
    end
  end

end
