require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SegmentsController do

  # This should return the minimal set of attributes required to create a valid
  # Segment. As you add validations to Segment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SegmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all segments as @segments" do
      segment = Segment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:segments).should eq([segment])
    end
  end

  describe "GET show" do
    it "assigns the requested segment as @segment" do
      segment = Segment.create! valid_attributes
      get :show, {:id => segment.to_param}, valid_session
      assigns(:segment).should eq(segment)
    end
  end

  describe "GET new" do
    it "assigns a new segment as @segment" do
      get :new, {}, valid_session
      assigns(:segment).should be_a_new(Segment)
    end
  end

  describe "GET edit" do
    it "assigns the requested segment as @segment" do
      segment = Segment.create! valid_attributes
      get :edit, {:id => segment.to_param}, valid_session
      assigns(:segment).should eq(segment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Segment" do
        expect {
          post :create, {:segment => valid_attributes}, valid_session
        }.to change(Segment, :count).by(1)
      end

      it "assigns a newly created segment as @segment" do
        post :create, {:segment => valid_attributes}, valid_session
        assigns(:segment).should be_a(Segment)
        assigns(:segment).should be_persisted
      end

      it "redirects to the created segment" do
        post :create, {:segment => valid_attributes}, valid_session
        response.should redirect_to(Segment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved segment as @segment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Segment.any_instance.stub(:save).and_return(false)
        post :create, {:segment => { "name" => "invalid value" }}, valid_session
        assigns(:segment).should be_a_new(Segment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Segment.any_instance.stub(:save).and_return(false)
        post :create, {:segment => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested segment" do
        segment = Segment.create! valid_attributes
        # Assuming there are no other segments in the database, this
        # specifies that the Segment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Segment.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => segment.to_param, :segment => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested segment as @segment" do
        segment = Segment.create! valid_attributes
        put :update, {:id => segment.to_param, :segment => valid_attributes}, valid_session
        assigns(:segment).should eq(segment)
      end

      it "redirects to the segment" do
        segment = Segment.create! valid_attributes
        put :update, {:id => segment.to_param, :segment => valid_attributes}, valid_session
        response.should redirect_to(segment)
      end
    end

    describe "with invalid params" do
      it "assigns the segment as @segment" do
        segment = Segment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Segment.any_instance.stub(:save).and_return(false)
        put :update, {:id => segment.to_param, :segment => { "name" => "invalid value" }}, valid_session
        assigns(:segment).should eq(segment)
      end

      it "re-renders the 'edit' template" do
        segment = Segment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Segment.any_instance.stub(:save).and_return(false)
        put :update, {:id => segment.to_param, :segment => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested segment" do
      segment = Segment.create! valid_attributes
      expect {
        delete :destroy, {:id => segment.to_param}, valid_session
      }.to change(Segment, :count).by(-1)
    end

    it "redirects to the segments list" do
      segment = Segment.create! valid_attributes
      delete :destroy, {:id => segment.to_param}, valid_session
      response.should redirect_to(segments_url)
    end
  end

end
