require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StudiesController do

  # This should return the minimal set of attributes required to create a valid
  # Studie. As you add validations to Studie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StudiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all studies as @studies" do
      studie = Studie.create! valid_attributes
      get :index, {}, valid_session
      assigns(:studies).should eq([studie])
    end
  end

  describe "GET show" do
    it "assigns the requested studie as @studie" do
      studie = Studie.create! valid_attributes
      get :show, {:id => studie.to_param}, valid_session
      assigns(:studie).should eq(studie)
    end
  end

  describe "GET new" do
    it "assigns a new studie as @studie" do
      get :new, {}, valid_session
      assigns(:studie).should be_a_new(Studie)
    end
  end

  describe "GET edit" do
    it "assigns the requested studie as @studie" do
      studie = Studie.create! valid_attributes
      get :edit, {:id => studie.to_param}, valid_session
      assigns(:studie).should eq(studie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Studie" do
        expect {
          post :create, {:studie => valid_attributes}, valid_session
        }.to change(Studie, :count).by(1)
      end

      it "assigns a newly created studie as @studie" do
        post :create, {:studie => valid_attributes}, valid_session
        assigns(:studie).should be_a(Studie)
        assigns(:studie).should be_persisted
      end

      it "redirects to the created studie" do
        post :create, {:studie => valid_attributes}, valid_session
        response.should redirect_to(Studie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved studie as @studie" do
        # Trigger the behavior that occurs when invalid params are submitted
        Studie.any_instance.stub(:save).and_return(false)
        post :create, {:studie => { "title" => "invalid value" }}, valid_session
        assigns(:studie).should be_a_new(Studie)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Studie.any_instance.stub(:save).and_return(false)
        post :create, {:studie => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested studie" do
        studie = Studie.create! valid_attributes
        # Assuming there are no other studies in the database, this
        # specifies that the Studie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Studie.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => studie.to_param, :studie => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested studie as @studie" do
        studie = Studie.create! valid_attributes
        put :update, {:id => studie.to_param, :studie => valid_attributes}, valid_session
        assigns(:studie).should eq(studie)
      end

      it "redirects to the studie" do
        studie = Studie.create! valid_attributes
        put :update, {:id => studie.to_param, :studie => valid_attributes}, valid_session
        response.should redirect_to(studie)
      end
    end

    describe "with invalid params" do
      it "assigns the studie as @studie" do
        studie = Studie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Studie.any_instance.stub(:save).and_return(false)
        put :update, {:id => studie.to_param, :studie => { "title" => "invalid value" }}, valid_session
        assigns(:studie).should eq(studie)
      end

      it "re-renders the 'edit' template" do
        studie = Studie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Studie.any_instance.stub(:save).and_return(false)
        put :update, {:id => studie.to_param, :studie => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested studie" do
      studie = Studie.create! valid_attributes
      expect {
        delete :destroy, {:id => studie.to_param}, valid_session
      }.to change(Studie, :count).by(-1)
    end

    it "redirects to the studies list" do
      studie = Studie.create! valid_attributes
      delete :destroy, {:id => studie.to_param}, valid_session
      response.should redirect_to(studies_url)
    end
  end

end
