require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StudyApplicationsController do

  # This should return the minimal set of attributes required to create a valid
  # StudyApplication. As you add validations to StudyApplication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "study_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StudyApplicationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all study_applications as @study_applications" do
      study_application = StudyApplication.create! valid_attributes
      get :index, {}, valid_session
      assigns(:study_applications).should eq([study_application])
    end
  end

  describe "GET show" do
    it "assigns the requested study_application as @study_application" do
      study_application = StudyApplication.create! valid_attributes
      get :show, {:id => study_application.to_param}, valid_session
      assigns(:study_application).should eq(study_application)
    end
  end

  describe "GET new" do
    it "assigns a new study_application as @study_application" do
      get :new, {}, valid_session
      assigns(:study_application).should be_a_new(StudyApplication)
    end
  end

  describe "GET edit" do
    it "assigns the requested study_application as @study_application" do
      study_application = StudyApplication.create! valid_attributes
      get :edit, {:id => study_application.to_param}, valid_session
      assigns(:study_application).should eq(study_application)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StudyApplication" do
        expect {
          post :create, {:study_application => valid_attributes}, valid_session
        }.to change(StudyApplication, :count).by(1)
      end

      it "assigns a newly created study_application as @study_application" do
        post :create, {:study_application => valid_attributes}, valid_session
        assigns(:study_application).should be_a(StudyApplication)
        assigns(:study_application).should be_persisted
      end

      it "redirects to the created study_application" do
        post :create, {:study_application => valid_attributes}, valid_session
        response.should redirect_to(StudyApplication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved study_application as @study_application" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudyApplication.any_instance.stub(:save).and_return(false)
        post :create, {:study_application => { "study_id" => "invalid value" }}, valid_session
        assigns(:study_application).should be_a_new(StudyApplication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudyApplication.any_instance.stub(:save).and_return(false)
        post :create, {:study_application => { "study_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested study_application" do
        study_application = StudyApplication.create! valid_attributes
        # Assuming there are no other study_applications in the database, this
        # specifies that the StudyApplication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StudyApplication.any_instance.should_receive(:update).with({ "study_id" => "1" })
        put :update, {:id => study_application.to_param, :study_application => { "study_id" => "1" }}, valid_session
      end

      it "assigns the requested study_application as @study_application" do
        study_application = StudyApplication.create! valid_attributes
        put :update, {:id => study_application.to_param, :study_application => valid_attributes}, valid_session
        assigns(:study_application).should eq(study_application)
      end

      it "redirects to the study_application" do
        study_application = StudyApplication.create! valid_attributes
        put :update, {:id => study_application.to_param, :study_application => valid_attributes}, valid_session
        response.should redirect_to(study_application)
      end
    end

    describe "with invalid params" do
      it "assigns the study_application as @study_application" do
        study_application = StudyApplication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudyApplication.any_instance.stub(:save).and_return(false)
        put :update, {:id => study_application.to_param, :study_application => { "study_id" => "invalid value" }}, valid_session
        assigns(:study_application).should eq(study_application)
      end

      it "re-renders the 'edit' template" do
        study_application = StudyApplication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudyApplication.any_instance.stub(:save).and_return(false)
        put :update, {:id => study_application.to_param, :study_application => { "study_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested study_application" do
      study_application = StudyApplication.create! valid_attributes
      expect {
        delete :destroy, {:id => study_application.to_param}, valid_session
      }.to change(StudyApplication, :count).by(-1)
    end

    it "redirects to the study_applications list" do
      study_application = StudyApplication.create! valid_attributes
      delete :destroy, {:id => study_application.to_param}, valid_session
      response.should redirect_to(study_applications_url)
    end
  end

end
